config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'homes#top'

  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    passwords: 'admins/passwords',
    registrations: 'admins/registrations'
  }

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }

  resources :customers
  resources :daily_reports do
    collection { get 'search' }
    resources :comments, only: %i[create destroy]
  end
  resources :items
  resources :suggest_items, only: %i[index new update destroy]

  post 'suggest_items' => 'suggest_items#create', as: 'create_suggest_items'
  get '/:current_users/my_page' => 'users#show', as: 'my_page'

  namespace :admin do
    resources :customers
    resources :items
    resources :users
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :daily_report

  validates :comment, presence: true
end

app/models/customer.rb
class Customer < ApplicationRecord
  belongs_to :user
  has_many :daily_reports, dependent: :destroy
  has_many :suggest_items, dependent: :destroy

  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  validates :name, presence: true
  validates :address, presence: true
  validates :postal_code, presence: true
  validates :telephone_number, presence: true
end

app/models/daily_report.rb
class DailyReport < ApplicationRecord
  belongs_to :customer
  belongs_to :user
  has_many :comments, dependent: :destroy

  def self.search(search)
    ret = DailyReport.all
    ret = ret.where(user_id: search[:user_id]) if search[:user_id] != ''
    ret = ret.where(customer_id: search[:customer_id]) if search[:customer_id] != ''
    ret
  end

  validates :content, presence: true
  validates :start_time, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  attachment :image
  has_many :suggest_items, dependent: :destroy

  validates :name, presence: true, uniqueness: true
  validates :content, presence: true
  validates :image, presence: true
end

app/models/suggest_item.rb
class SuggestItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer

  enum status: {
    "提案済": 0,
    "検討中": 1,
    "見積済": 2,
    "価格交渉中": 3,
    "切替済": 4,
    "切替失敗": 5
  }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :customers, dependent: :destroy
  has_many :daily_reports, dependent: :destroy
  has_many :comments, dependent: :destroy
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    daily_report = DailyReport.find(params[:daily_report_id])
    comment = current_user.comments.new(comment_params)
    comment.daily_report_id = daily_report.id
    if comment.save
      redirect_to daily_report_path(daily_report)
    else
      redirect_to daily_report_path(daily_report)
    end
  end

  def destroy; end

  private

  def comment_params
    params.require(:comment).permit(:comment)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.page(params[:page])
  end

  def show
    @item = Item.find(params[:id])
  end

  private

  def item_params
    params.require(:item).permit(:name, :content, :image)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @customers = Customer.all
    @customers = current_user.customers

    @daily_reports = DailyReport.all
    @daily_reports = current_user.daily_reports
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/daily_reports_helper.rb
module DailyReportsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/suggest_items_helper.rb
module SuggestItemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SalesBrain</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="border-bottom header">
       <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
         <div class="title">SalesBrain <i class="fas fa-brain" ></i></div>
         <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
         </button>
         <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav ml-auto">
           <% if admin_signed_in? %>
            <li class="nav-item btn">
             <%= link_to "ユーザー一覧", admin_users_path, class: 'nav-link text-dark' %>
            </li>

            <li class="nav-item btn">
             <%= link_to "得意先一覧", admin_customers_path, class: 'nav-link text-dark' %>
            </li>

            <li class="nav-item btn">
             <%= link_to "商品一覧", admin_items_path, class: 'nav-link text-dark' %>
            </li>

            <li class="nav-item btn">
             <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'nav-link text-dark' %>
            </li>
           <% elsif user_signed_in? %>
            <li class="nav-item btn">
             <%= link_to "マイページ", my_page_path(current_user.id), class: 'nav-link text-dark' %>
            </li>

            <li class="nav-item btn">
             <%= link_to "日報一覧", daily_reports_path, class: 'nav-link text-dark' %>
            </li>

            <li class="nav-item btn">
             <%= link_to "得意先一覧", customers_path, class: 'nav-link text-dark' %>
            </li>

            <li class="nav-item btn">
             <%= link_to "商品一覧", items_path, class: 'nav-link text-dark' %>
            </li>

            <li class="nav-item btn">
             <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'nav-link text-dark' %>
            </li>
           <% else %>
            <li class="nav-item btn">
             <%= link_to "ログイン", new_user_session_path, class: 'nav-link text-dark' %>
            </li>

            <li class="nav-item btn">
             <%= link_to "新規登録", new_user_registration_path, class: 'nav-link text-dark' %>
            </li>
           <% end %>
          </ul>
         </div>
       </div>
      </nav>
   </header>
   <%= yield %>
   <footer class="border-top footer">
    <div class="container mt-5">
     <div class="row">
      <div class="col-sm-12"></div>
     </div>
    </div>
   </footer>
  </body>
</html>

<style type="text/css">

 .header {
  background-color: #3fcc9d;
 }

 .footer {
  background-color: #3fcc9d;
 }

 .title {
  font-family: impact;
  font-size: 30px;
 }

 .nav-item {
  font-family: Hiragino Kaku Gothic Std;
  font-color: white;
 }
</style>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<style type="text/css">

 .calendar-heading {
  font-family: Hiragino Kaku Gothic Std;
  font-size: 15px;
 }

</style>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %></span>
    <% else %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <% end %>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>