config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'homes#top'

  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    passwords: 'admins/passwords',
    registrations: 'admins/registrations'
  }

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }

  resources :customers
  resources :daily_reports do
    collection { get 'search' }
    resources :comments, only: %i[create destroy]
  end
  resources :items
  resources :suggest_items, only: %i[index new update destroy]

  post 'suggest_items' => 'suggest_items#create', as: 'create_suggest_items'
  get '/:current_users/my_page' => 'users#show', as: 'my_page'

  namespace :admin do
    resources :customers
    resources :items
    resources :users
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :customers, dependent: :destroy
  has_many :daily_reports, dependent: :destroy
  has_many :comments, dependent: :destroy
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!, except: [:top]

  def index
    @users = User.page(params[:page])
  end

  def show
    @user = User.find(params[:id])
    @customers = Customer.all
    @customers = @user.customers
  end

  private

  def user_params
    params.require(:user).permit(:name, :number)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @customers = Customer.all
    @customers = current_user.customers

    @daily_reports = DailyReport.all
    @daily_reports = current_user.daily_reports
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/index.html.erb
<div class="container">
 <div class="row">
  <div class="col-sm-4 col-lg-3 mt-3 mb-3">
   <h3 class="title-user">営業マン一覧</h3>
  </div>
 </div>
</div>

<div class="container">
 <div class="row">
  <div class="col-sm-10 mx-auto">
   <table class="table">
    <thead>
     <tr class="title-bar">
      <th>社員番号</th>
      <th>名前</th>
      <th></th>
     </tr>
    </thead>

    <tbody>
     <% @users.each do |user| %>
      <tr>
       <th><%= user.number %></th>
       <th><%= user.name %></th>
       <th class="text-center"><%= link_to "詳細", admin_user_path(user.id) %></th>
      </tr>
     <% end %>
    </tbody>
   </table>
  </div>
 </div>
</div>

<div class="container">
 <div class="row">
  <div class="col-sm-10 mx-auto mb-3">
   <div class="col-2 mx-auto page"><%= paginate @users %></div>
  </div>
 </div>
</div>

<style type="text/css">

 .title-user {
  background:linear-gradient(45deg, #4fffc4, #fff);
  font-family: YuGothic;
 }

 .title-bar {
  background-color: #3fcc9d;
 }

 .page {
  font-family: HiraKakuPro-W6;
 }

</style>

app/views/admin/users/show.html.erb
<div class="container">
 <div class="row">
  <div class="col-sm-4 col-lg-3 mt-3 mb-3">
   <h3 class="title-user">営業マン詳細</h3>
  </div>
 </div>
</div>

<div class="container">
 <div class="row">
  <div class="col-sm-3 col-lg-2 mt-5 mb-3">
   <h4 class="title-user">〜詳細〜</h4>
  </div>
 </div>
</div>

<%= form_with model:[:admin, @user], local:true do |f| %>
 <div class="container">
  <div class="row">
   <div class="col-sm-7 col-lg-5 col-mg-3">
    <table class="table-bordered col-sm-9">
     <tr height="50">
      <th><%= f.label "社員番号" %></th><th><%= @user.number %></th>
  　  </tr>
     <tr height="50">
      <th><%= f.label "営業マン" %></th><th><%= @user.name %></th>
     </tr>
    </table>
   </div>
  </div>
 </div>
<% end %>

<div class="container">
 <div class="row">
  <div class="col-sm-3 col-lg-2 mt-5 mb-3">
   <h4 class="title-user">〜担当客先〜</h4>
  </div>
 </div>
</div>

<div class="container">
 <div class="row">
  <div class="col-sm-7 col-lg-5 box">
   <table class="table">
    <thead>
     <tr class="title-bar">
      <th>担当得意先名</th>
      <th>編集</th>
     </tr>
    </thead>

    <tbody>
     <% @customers.each do |customer| %>
      <tr>
       <th><%= customer.name %></th>
       <th><%= link_to "編集", edit_admin_customer_path(customer.id) %></th>
      </tr>
     <% end %>
    </tbody>
   </table>
  </div>
 </div>
</div>

<div class="container">
 <div class="row">
  <div class="col-sm-7 col-lg-5 mt-3 mb-5">
   <div class="text-center"><%= link_to "一覧に戻る", admin_users_path, class: "btn btn-primary" %></div>
  </div>
 </div>
</div>

<style type="text/css">
 .box {
  height: 200px;
  border: 1px solid #000;
  overflow-y: scroll;
 }

 .title-user {
  background:linear-gradient(45deg, #4fffc4, #fff);
  font-family: YuGothic;
 }

.title-bar {
  background-color: #3fcc9d;
 }
</style>