config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'homes#top'

  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    passwords: 'admins/passwords',
    registrations: 'admins/registrations'
  }

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }

  resources :customers
  resources :daily_reports do
    collection { get 'search' }
    resources :comments, only: %i[create destroy]
  end
  resources :items
  resources :suggest_items, only: %i[index new update destroy]

  post 'suggest_items' => 'suggest_items#create', as: 'create_suggest_items'
  get '/:current_users/my_page' => 'users#show', as: 'my_page'

  namespace :admin do
    resources :customers
    resources :items
    resources :users
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :daily_report

  validates :comment, presence: true
end

app/models/customer.rb
class Customer < ApplicationRecord
  belongs_to :user
  has_many :daily_reports, dependent: :destroy
  has_many :suggest_items, dependent: :destroy

  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  validates :name, presence: true
  validates :address, presence: true
  validates :postal_code, presence: true
  validates :telephone_number, presence: true
end

app/models/daily_report.rb
class DailyReport < ApplicationRecord
  belongs_to :customer
  belongs_to :user
  has_many :comments, dependent: :destroy

  def self.search(search)
    ret = DailyReport.all
    ret = ret.where(user_id: search[:user_id]) if search[:user_id] != ''
    ret = ret.where(customer_id: search[:customer_id]) if search[:customer_id] != ''
    ret
  end

  validates :content, presence: true
  validates :start_time, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  attachment :image
  has_many :suggest_items, dependent: :destroy

  validates :name, presence: true, uniqueness: true
  validates :content, presence: true
  validates :image, presence: true
end

app/models/suggest_item.rb
class SuggestItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer

  enum status: {
    "提案済": 0,
    "検討中": 1,
    "見積済": 2,
    "価格交渉中": 3,
    "切替済": 4,
    "切替失敗": 5
  }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :customers, dependent: :destroy
  has_many :daily_reports, dependent: :destroy
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    case resource
    when Admin
      root_path
    when User
      my_page_path(current_user)
    end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name number])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    daily_report = DailyReport.find(params[:daily_report_id])
    comment = current_user.comments.new(comment_params)
    comment.daily_report_id = daily_report.id
    if comment.save
      redirect_to daily_report_path(daily_report)
    else
      redirect_to daily_report_path(daily_report)
    end
  end

  def destroy; end

  private

  def comment_params
    params.require(:comment).permit(:comment)
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def index
    @customers = Customer.page(params[:page])
  end

  def show
    @customer = Customer.find(params[:id])
    @suggest_item = SuggestItem.new
    @suggest_items = SuggestItem.all
    @suggest_items = @customer.suggest_items
  end

  private

  def customer_params
    params.require(:customer).permit(:user_id, :name, :address, :postal_code, :telephone_number)
  end
end

app/controllers/daily_reports_controller.rb
class DailyReportsController < ApplicationController
  before_action :set_daily_report, only: %i[edit show destroy update]

  def new
    @daily_report = DailyReport.new
  end

  def index
    @daily_reports = DailyReport.all.page(params[:page]).order(start_time: :desc)
  end

  def show
    @daily_report = DailyReport.find(params[:id])
    @comment = Comment.new
  end

  def edit
    @daily_report = DailyReport.find(params[:id])
  end

  def create
    @daily_report = DailyReport.new(daily_report_params)
    if @daily_report.save
      redirect_to daily_report_path(@daily_report.id)
    else
      render :new
    end
  end

  def update
    @daily_report = DailyReport.find(params[:id])
    if @daily_report.update(daily_report_params)
      redirect_to daily_report_path(@daily_report.id)
    else
      render :edit
    end
  end

  def destroy; end

  def search
    @daily_reports = DailyReport.search(params).page(params[:page]).order(start_time: :desc)
    render 'index'
  end

  private

  def daily_report_params
    params.require(:daily_report).permit(:user_id, :customer_id, :content, :start_time)
  end

  def set_daily_report
    @daily_report = DailyReport.find(params[:id])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.page(params[:page])
  end

  def show
    @item = Item.find(params[:id])
  end

  private

  def item_params
    params.require(:item).permit(:name, :content, :image)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @customers = Customer.all
    @customers = current_user.customers

    @daily_reports = DailyReport.all
    @daily_reports = current_user.daily_reports
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/daily_reports_helper.rb
module DailyReportsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/suggest_items_helper.rb
module SuggestItemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/daily_reports/edit.html.erb
<div class="container">
 <div class="row">
  <div class="col-sm-3 col-lg-2 mt-3 mb-3">
   <h3 class="title-user">日報編集</h3>
  </div>
 </div>
</div>

<div class="container">
 <div class="row">
  <div class="col-sm-6 mt-3">
   <% if @daily_report.errors.any? %>
    <%= @daily_report.errors.count %>件のエラーが発生しました</br>
    <% @daily_report.errors.full_messages.each do |message| %>
     <%= message %></br>
    <% end %>
   <% end %>
  </div>
 </div>
</div>

<%= form_with model: @daily_report, local:true do |f| %>

<div class="container">
  <div class="row">
   <table class="col-sm-12 col-mg-8 mt-sm-5 mb-5">
    <tr height="50">
     <th><%= f.label "訪問日時" %></th>
     <th><%= f.datetime_field :start_time %></th>
    </tr>
    <tr height="50">
     <th><%= f.label "得意先" %></th><th><%= @daily_report.customer.name %></th>
    </tr>
    <tr height="50">
     <th><%= f.label "訪問内容" %></th><th><%= f.text_area :content %></th>
    </tr>

    <tr height="50">
     <th><%= f.submit "更新", class: "btn btn-success" %></th>
     <th><%= link_to "一覧に戻る", daily_reports_path, class: "btn btn-primary" %></th>
    </tr>
   </table>
  </div>
 </div>
<% end %>

<style type="text/css">

 .title-user {
  background:linear-gradient(45deg, #4fffc4, #fff);
  font-family: YuGothic;
 }

 .title-bar {
  background-color: #3fcc9d;
 }

</style>

app/views/daily_reports/index.html.erb
<div class="container">
 <div class="row">
  <div class="col-sm-3 col-lg-2 mt-3 mb-3">
   <h3 class="title-user">日報一覧</h3>
  </div>
 </div>
</div>

<div class="container">
 <div class="row">
  <div class="col-sm-10 mx-auto mb-3">

    <%= form_with(url: search_daily_reports_path, local: true, method: :get, class:"search-form")  do |f| %>
     <%= f.select :user_id, options_from_collection_for_select(User.all, :id, :name), include_blank: "" %>
     <%= f.select :customer_id, options_from_collection_for_select(Customer.all, :id, :name), include_blank: "" %>
     <%= f.submit "検索" %>
    <% end %>

  </div>
 </div>
</div>

<div class="container">
 <div class="row">
  <div class="col-sm-10 mx-auto mb-3">
   <div class="text-right"><%= link_to "新規登録", new_daily_report_path, class: "btn btn-primary" %></div>
  </div>
 </div>
</div>


<div class="container">
 <div class="row">
  <div class="col-sm-10 mx-auto">
   <table class="table">
    <thead>
     <tr class="title-bar">
      <th>担当者名</th>
      <th>得意先名</th>
      <th></th>
     </tr>
    </thead>

    <tbody>
     <% @daily_reports.each do |daily_report| %>
      <tr>
       <th><%= daily_report.user.name %></th>
       <th><%= daily_report.customer.name %></th>
       <th><%= link_to "詳細", daily_report_path(daily_report.id) %></th>
      </tr>
     <% end %>
    </tbody>
   </table>
  </div>
 </div>
</div>

<div class="container">
 <div class="row">
  <div class="col-sm-10 mx-auto mb-3">
   <div class="col-2 mx-auto page"><%= paginate @daily_reports %></div>
  </div>
 </div>
</div>

<style type="text/css">

 .title-user {
  background:linear-gradient(45deg, #4fffc4, #fff);
  font-family: YuGothic;
 }

 .title-bar {
  background-color: #3fcc9d;
 }

 .page {
  font-family: HiraKakuPro-W6;
 }

</style>

app/views/daily_reports/new.html.erb
<div class="container">
 <div class="row">
  <div class="col-sm-6 mt-3">
   <h3>日報新規登録</h3>
  </div>
 </div>
</div>

<div class="container">
 <div class="row">
  <div class="col-sm-6 mt-3">
   <% if @daily_report.errors.any? %>
    <%= @daily_report.errors.count %>件のエラーが発生しました</br>
    <% @daily_report.errors.full_messages.each do |message| %>
     <%= message %></br>
    <% end %>
   <% end %>
  </div>
 </div>
</div>

<%= form_with model: @daily_report, local:true do |f| %>

 <%= f.hidden_field :user_id, value: current_user.id %>
 <div class="container">
  <div class="row">
   <table class="col-sm-12 col-mg-8 mt-sm-5">
    <tr height="50">
     <th><%= f.label "訪問日時" %></th>
     <th><%= f.datetime_field :start_time %></th>
    </tr>
    <tr height="50">
     <th><%= f.label "得意先" %></th>
     <th><%= f.select :customer_id, options_from_collection_for_select(Customer.all, :id, :name) %></th>
    </tr>
    <tr height="50">
     <th><%= f.label "訪問内容" %></th>
     <th><%= f.text_area :content %></th>
    </tr>
    <tr height="50">
     <th><%= f.submit "登録", class: "btn btn-success" %></th>
     <th><%= link_to "一覧に戻る", daily_reports_path, class: "btn btn-primary" %></th>
    </tr>
   </table>
  </div>
 </div>
<% end %>

app/views/daily_reports/show.html.erb
<div class="container">
 <div class="row">
  <div class="col-sm-3 col-lg-2 mt-3 mb-3">
   <h3 class="title-user">日報詳細</h3>
  </div>
 </div>
</div>

<div class="container">
 <div class="row">
  <div class="col-sm-3 col-lg-2 mt-5 mb-3">
   <h4 class="title-user">〜日報内容〜</h4>
  </div>
 </div>
</div>

<%= form_with model:@daily_report, local:true do |f| %>
 <div class="container">
  <div class="row">
   <div class="col-sm-10 col-md-10 col-lg-8 mt-sm-5">
    <table class="col-sm-12 table-bordered">
     <tr height="50">
      <th class="col-sm-4">担当者</th>
      <th class="col-sm-8"><%= @daily_report.user.name %></th>
     </tr>

     <tr height="50">
      <th class="col-sm-4">訪問先</th>
      <th class="col-sm-8"><%= link_to @daily_report.customer.name, customer_path(@daily_report.customer.id) %></th>
     </tr>

     <tr height="50">
      <th class="col-sm-4">訪問日時</th>
      <th class="col-sm-8"><%= @daily_report.start_time %></th>
     </tr>

     <tr height="50">
      <th class="col-sm-4">訪問内容</th>
      <th class="col-sm-8 content"><%= @daily_report.content %></th>
     </tr>
     <tr height="50">
      <th><%= link_to "編集する", edit_daily_report_path(@daily_report.id), class: "btn btn-success" %></th>
      <th><%= link_to "一覧に戻る", daily_reports_path, class: "btn btn-primary" %></th>
     </tr>
    </div>
   </table>
  </div>
 </div>

<% end %>

<div class="container">
 <div class="row">
  <div class="col-sm-4 col-lg-3 mt-5 mb-3">
   <h4 class="title-user">〜コメント一覧〜</h4>
  </div>
 </div>
</div>

<div class="container flash-area">
 <% flash.each do |message_type, message| %>
  <div class="aleart aleart-<%= message_type %>">
   <%= message %>
  </div>
 <% end %>
</div>

 <div class="container">
  <div class="row">
   <div class="col-sm-10 col-md-10 col-lg-8 mt-sm-5">
    <table class="col-sm-12 table-bordered">
     <tr class="title-bar">
      <th class="col-sm-3">投稿日時</th>
      <th class="col-sm-3">投稿者名</th>
      <th class="col-sm-6">コメント内容</th>
     </tr>
     <% @daily_report.comments.each do |comment| %>
      <tr>
       <th class="col-sm-3"><%= comment.created_at.strftime('%Y/%m/%d') %></th>
       <th class="col-sm-3"><%= comment.user.name %></th>
       <th class="col-sm-6 comment"><%= comment.comment %></th>
      </tr>
     <% end %>
    </div>
   </table>
  </div>
 </div>

<div class="container">
 <div class="row">
  <div class="box col-sm-8 col-md-6 col-lg-4 mt-sm-3 mb-sm-3">
   <%= form_with(model:[@daily_report, @comment], local: true) do |f| %>
    <%= f.text_area :comment %>
    <%= f.submit "コメントする" %>
   <% end %>
  </div>
 </div>
</div>

<style type="text/css">
 .content {
  word-break: break-all;
 }

 .comment {
  word-break: break-all;
 }

 .title-user {
  background:linear-gradient(45deg, #4fffc4, #fff);
  font-family: YuGothic;
 }

 .title-bar {
  background-color: #3fcc9d;
 }
</style>